ALTER TABLE drivers
  ADD COLUMN IF NOT EXISTS short_name TEXT,
  ADD COLUMN IF NOT EXISTS team_color TEXT,
  ADD COLUMN IF NOT EXISTS nationality TEXT,
  ADD COLUMN IF NOT EXISTS flag TEXT,
  ADD COLUMN IF NOT EXISTS points INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS position INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS wins INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS podiums INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS poles INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS championships INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS dob TEXT,
  ADD COLUMN IF NOT EXISTS pob TEXT,
  ADD COLUMN IF NOT EXISTS gp_entered INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS career_points TEXT NOT NULL DEFAULT '0',
  ADD COLUMN IF NOT EXISTS best_finish TEXT NOT NULL DEFAULT '—',
  ADD COLUMN IF NOT EXISTS best_grid TEXT NOT NULL DEFAULT '—',
  ADD COLUMN IF NOT EXISTS dnfs INTEGER NOT NULL DEFAULT 0;

UPDATE drivers
SET
  short_name = COALESCE(short_name, code),
  team_color = COALESCE(team_color, '#999999'),
  nationality = COALESCE(nationality, country),
  flag = COALESCE(flag, '🏁'),
  dob = COALESCE(dob, '01/01/1900'),
  pob = COALESCE(pob, 'Unknown');

ALTER TABLE drivers
  ALTER COLUMN short_name SET NOT NULL,
  ALTER COLUMN team_color SET NOT NULL,
  ALTER COLUMN nationality SET NOT NULL,
  ALTER COLUMN flag SET NOT NULL,
  ALTER COLUMN dob SET NOT NULL,
  ALTER COLUMN pob SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS drivers_short_name_unique_idx
  ON drivers(short_name);
