export interface TeamProfileData {
  name: string
  color: string
  points: number
  position: number
  driver1: string
  driver2: string
  wins: number
  podiums: number
  base: string
  fullName: string
  teamChief: string
  technicalChief: string
  chassis: string
  powerUnit: string
  firstEntry: string
  championships: number
}

export const teamProfilesData: TeamProfileData[] = [
  {
    name: "McLaren",
    color: "#FF8000",
    points: 0,
    position: 1,
    driver1: "L. Norris",
    driver2: "O. Piastri",
    wins: 0,
    podiums: 0,
    base: "Woking, United Kingdom",
    fullName: "McLaren Mastercard F1 Team",
    teamChief: "Andrea Stella",
    technicalChief: "Peter Prodromou / Neil Houldey",
    chassis: "MCL40",
    powerUnit: "Mercedes",
    firstEntry: "1966",
    championships: 10,
  },
  {
    name: "Mercedes",
    color: "#27F4D2",
    points: 0,
    position: 2,
    driver1: "G. Russell",
    driver2: "K. Antonelli",
    wins: 0,
    podiums: 0,
    base: "Brackley, United Kingdom",
    fullName: "Mercedes-AMG PETRONAS Formula One Team",
    teamChief: "Toto Wolff",
    technicalChief: "James Allison",
    chassis: "W17",
    powerUnit: "Mercedes",
    firstEntry: "1970",
    championships: 8,
  },
  {
    name: "Red Bull Racing",
    color: "#3671C6",
    points: 0,
    position: 3,
    driver1: "M. Verstappen",
    driver2: "I. Hadjar",
    wins: 0,
    podiums: 0,
    base: "Milton Keynes, United Kingdom",
    fullName: "Oracle Red Bull Racing",
    teamChief: "Laurent Mekies",
    technicalChief: "Pierre Waché",
    chassis: "RB22",
    powerUnit: "Red Bull Ford",
    firstEntry: "1997",
    championships: 6,
  },
  {
    name: "Ferrari",
    color: "#E8002D",
    points: 0,
    position: 4,
    driver1: "C. Leclerc",
    driver2: "L. Hamilton",
    wins: 0,
    podiums: 0,
    base: "Maranello, Italy",
    fullName: "Scuderia Ferrari HP",
    teamChief: "Frédéric Vasseur",
    technicalChief: "Loic Serra / Enrico Gualtieri",
    chassis: "SF-26",
    powerUnit: "Ferrari",
    firstEntry: "1950",
    championships: 16,
  },
  {
    name: "Williams",
    color: "#64C4FF",
    points: 0,
    position: 5,
    driver1: "C. Sainz",
    driver2: "A. Albon",
    wins: 0,
    podiums: 0,
    base: "Grove, United Kingdom",
    fullName: "Atlassian Williams F1 Team",
    teamChief: "James Vowles",
    technicalChief: "Pat Fry",
    chassis: "FW48",
    powerUnit: "Mercedes",
    firstEntry: "1978",
    championships: 9,
  },
  {
    name: "Racing Bulls",
    color: "#6692FF",
    points: 0,
    position: 6,
    driver1: "L. Lawson",
    driver2: "A. Lindblad",
    wins: 0,
    podiums: 0,
    base: "Faenza, Italy",
    fullName: "Visa Cash App Racing Bulls Formula One Team",
    teamChief: "Alan Permane",
    technicalChief: "Tim Goss",
    chassis: "VCARB 03",
    powerUnit: "Red Bull Ford",
    firstEntry: "1985",
    championships: 0,
  },
  {
    name: "Aston Martin",
    color: "#229971",
    points: 0,
    position: 7,
    driver1: "F. Alonso",
    driver2: "L. Stroll",
    wins: 0,
    podiums: 0,
    base: "Silverstone, United Kingdom",
    fullName: "Aston Martin Aramco Formula One Team",
    teamChief: "Adrian Newey",
    technicalChief: "Enrico Cardile",
    chassis: "AMR26",
    powerUnit: "Honda",
    firstEntry: "2018",
    championships: 0,
  },
  {
    name: "Haas F1 Team",
    color: "#B6BABD",
    points: 0,
    position: 8,
    driver1: "E. Ocon",
    driver2: "O. Bearman",
    wins: 0,
    podiums: 0,
    base: "Kannapolis, United States",
    fullName: "TGR Haas F1 Team",
    teamChief: "Ayao Komatsu",
    technicalChief: "Andrea De Zordo",
    chassis: "VF-26",
    powerUnit: "Ferrari",
    firstEntry: "2016",
    championships: 0,
  },
  {
    name: "Audi",
    color: "#C00000",
    points: 0,
    position: 9,
    driver1: "N. Hulkenberg",
    driver2: "G. Bortoleto",
    wins: 0,
    podiums: 0,
    base: "Hinwil, Switzerland",
    fullName: "Audi Revolut F1 Team",
    teamChief: "Jonathan Wheatley",
    technicalChief: "James Key",
    chassis: "R26",
    powerUnit: "Audi",
    firstEntry: "2026",
    championships: 0,
  },
  {
    name: "Alpine",
    color: "#FF87BC",
    points: 0,
    position: 10,
    driver1: "P. Gasly",
    driver2: "F. Colapinto",
    wins: 0,
    podiums: 0,
    base: "Enstone, United Kingdom",
    fullName: "BWT Alpine Formula One Team",
    teamChief: "Flavio Briatore",
    technicalChief: "David Sanchez",
    chassis: "A526",
    powerUnit: "Mercedes",
    firstEntry: "1986",
    championships: 2,
  },
  {
    name: "Cadillac",
    color: "#FFFFFF",
    points: 0,
    position: 11,
    driver1: "S. Perez",
    driver2: "V. Bottas",
    wins: 0,
    podiums: 0,
    base: "Kannapolis, United States",
    fullName: "Cadillac Formula 1 Team",
    teamChief: "Graeme Lowdon",
    technicalChief: "Nick Chester",
    chassis: "TBC",
    powerUnit: "Ferrari",
    firstEntry: "2026",
    championships: 0,
  },
]
